### ISSUE TITLE
Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock

### ISSUE THREAD

**Issue by promzeus** [diseq/csi-rclone#2]
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392135 2169873 reconciler.go:181] operationExecutor.UnmountVolume started for volume "webroot" (UniqueName: "kubernetes.io/csi/ch.ctrox.csi.s3-driver^pvc-fb0d20c6-030b-4489-97cc-f9844b9bb46d") pod "d2360244-6f40-4e64-9d23-5ccf8b8099fd" (UID: "d2360244-6f40-4e64-9d23-5ccf8b8099fd")
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392252 2169873 clientconn.go:104] parsed scheme: ""
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392272 2169873 clientconn.go:104] scheme "" not registered, fallback to default scheme
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392316 2169873 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock 0  <nil>}] <nil>}
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392328 2169873 clientconn.go:577] ClientConn switching balancer to "pick_first"
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392375 2169873 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001031b90, CONNECTING
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: W1214 13:18:01.392494 2169873 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock: connect: connection refused". Reconnecting...
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: I1214 13:18:01.392521 2169873 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001031b90, TRANSIENT_FAILURE
Dec 14 13:18:01 dev-black-hole kubelet[2169873]: E1214 13:18:01.392596 2169873 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/ch.ctrox.csi.s3-driver^pvc-fb0d20c6-030b-4489-97cc-f9844b9bb46d\" (\"d2360244-6f40-4e64-9d23-5ccf8b8099fd\")" failed. No retries permitted until 2020-12-14 13:20:03.392565649 +0000 UTC m=+1179499.616871304 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"webroot\" (UniqueName: \"kubernetes.io/csi/ch.ctrox.csi.s3-driver^pvc-fb0d20c6-030b-4489-97cc-f9844b9bb46d\") pod \"d2360244-6f40-4e64-9d23-5ccf8b8099fd\" (UID: \"d2360244-6f40-4e64-9d23-5ccf8b8099fd\") : kubernetes.io/csi: mounter.TearDownAt failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock: connect: connection refused\""

**Comment by diseq** [comment]
seems to be an error in the csi driver "ch.ctrox.csi.s3-driver" you are using.
